ln -s ../remote/pub_topic_control_buzzer.sh pub_topic_control_buzzer.sh
ln -s ../remote/pub_topic_control_led.sh pub_topic_control_led.sh
ln -s ../remote/save_map.sh save_map.sh
ln -s ../remote/start_nav_square_use_move_base.sh start_nav_square_use_move_base.sh
ln -s ../remote/start_nav_square_use_odom.sh start_nav_square_use_odom.sh
ln -s ../remote/start_odom_out_and_back.sh start_odom_out_and_back.sh
ln -s ../remote/start_take_panorama_by_call_service.sh start_take_panorama_by_call_service.sh
ln -s ../remote/start_take_panorama_by_pub_topic.sh start_take_panorama_by_pub_topic.sh
ln -s ../remote/stop_take_panorama_by_call_service.sh stop_take_panorama_by_call_service.sh
ln -s ../remote/stop_take_panorama_by_pub_topic.sh stop_take_panorama_by_pub_topic.sh
ln -s ../remote/view_krb100m_in_rviz.sh view_krb100m_in_rviz.sh
